# Generated by Django 4.0.6 on 2022-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='post',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
